twig:
    file_name_pattern: '*.twig'
    globals:
        cart: '@App\Service\Cart'
        notifications_repo: '@App\Repository\NotificationRepository'

when@test:
    twig:
        strict_variables: true
