<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260418200614 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE order_events (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(30) NOT NULL, summary VARCHAR(255) NOT NULL, data JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, order_id INT NOT NULL, actor_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9008479F8D9F6D38 ON order_events (order_id)');
        $this->addSql('CREATE INDEX IDX_9008479F10DAF24A ON order_events (actor_id)');
        $this->addSql('CREATE INDEX idx_oe_order_created ON order_events (order_id, created_at)');
        $this->addSql('ALTER TABLE order_events ADD CONSTRAINT FK_9008479F8D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_events ADD CONSTRAINT FK_9008479F10DAF24A FOREIGN KEY (actor_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE order_events DROP CONSTRAINT FK_9008479F8D9F6D38');
        $this->addSql('ALTER TABLE order_events DROP CONSTRAINT FK_9008479F10DAF24A');
        $this->addSql('DROP TABLE order_events');
    }
}
